version: '3.7'

services:
   ivantest:
    image: ivantest
    build:
      context: .
      dockerfile: Clien-Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"