# This workflow will build and run tests for this app.
# TODO: Add deployment jobs for production use.

name: CI

permissions:
  id-token: write
  contents: read
  statuses: write
  checks: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore KanbanBoard/KanbanBoard.sln
    - name: Build
      run: dotnet build KanbanBoard/KanbanBoard.sln --no-restore
    - name: Test
      run: dotnet test KanbanBoard/KanbanBoard.sln --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        
      with:
        name: test-results
        path: KanbanBoard/Tests/*/TestResults/test-results.trx
