name: 'Test Report'

permissions:
  id-token: write
  contents: read
  statuses: write
  checks: write

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: TRX Tests
        path: '**/test-results.trx'
        reporter: dotnet-trx